# docker-compose.yml

version: '3'
services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1045:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/localhost.crt:/etc/nginx/ssl/localhost.crt
      - ./ssl/localhost.key:/etc/nginx/ssl/localhost.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - node_app
